### PR TITLE
fluto 2.0

### PR DESCRIPTION
**Pull request by sthiele**
- adds the topological producibility criteria sagot and fluto1
- adds json output
- replaces pyasp with clyngor
- use latest clingo-lp from potassco instead shipping our own implementation
- sets up ci tests
- add support for enumeration of optimal solutions
- add brave and cautious reasoning modes  (union resp. intersection of completions)

### CODE REVIEW

**Comment by sthiele** [comment]
@cfrioux  I think this is ready. This has become a pretty big PR. Let me know if you want to discuss this some more.

**Comment by cfrioux** [comment]
Hi Sven, great work with the package! 
You will see that I committed minor changes. I still have one worry. The way the -c option results display is confusing. One might think that the reactions from the intersection are enough to activate the objective.
See:

```
fluto -m data/toy/draft.xml -s data/toy/toposeeds.txt -r data/toy/repairdb.xml  -c
# Fluto analysis

1 topological seed(s) was(were) provided
Model file: data/toy/draft.xml
Objective reaction(s): R5
Seeds file: data/toy/toposeeds.txt
Repair DB: data/toy/repairdb.xml

Topological criterium: Handorf
Reasoning mode: CAUTIOUS
Flux balance criterium: ON
Accumulation: ALLOWED
Solving ...

1 solutions found


## Solution 1

- flux value in objective function(s): 49999.5

- 2 producible targets:
  - a
  - c

- all targets are producible

- 2 reactions to be added:
  - R6
  - R9

- no metabolites are accumulating
```

I also wonder whether the "no ametabolite is accumulating" log is clear enough. Technically depending on the chosen algorithm there might be accumulation that will not be checked. Having this message at the end could be erroneous what do you think?

**Comment by sthiele** [comment]
> I still have one worry. The way the -c option results display is confusing. One might think that the reactions from the intersection are enough to activate the objective.
...
> I also wonder whether the "no ametabolite is accumulating" log is clear enough. Technically depending on the chosen algorithm there might be accumulation that will not be checked. Having this message at the end could be erroneous what do you think?

I see what you mean. Let me know if you have ideas how to solve this. I could imagine a warning when using cautious reasoning?

**Comment by cfrioux** [comment]
What if we gave the list of reactions differently for cautious and brave modes?
"Reactions occurring in all minimal solutions (intersection): R6, R9"
"Reactions occurring in at least one minimal solution (union): [...]"
instead of 

```
- 2 reactions to be added:
  - R6
  - R9
```

**Comment by sthiele** [comment]
Sounds good. I implemented your suggestion and now the output for brave and cautious looks like this:

`fluto -m data/toy/draft.xml -s data/toy/toposeeds.txt -r data/toy/repairdb.xml --brave > result.md`
# Fluto analysis

Model file: data/toy/draft.xml
Objective reaction(s): R5
Seeds file: data/toy/toposeeds.txt
Repair DB: data/toy/repairdb.xml

Topological criterium: Handorf
Reasoning mode: BRAVE
Flux balance criterium: ON
Accumulation: ALLOWED

## Reactions occurring in at least one minimal solution (union):

- R8
- R6
- R9
- R7

`fluto -m data/toy/draft.xml -s data/toy/toposeeds.txt -r data/toy/repairdb.xml --cautious > result.md`
# Fluto analysis

Model file: data/toy/draft.xml
Objective reaction(s): R5
Seeds file: data/toy/toposeeds.txt
Repair DB: data/toy/repairdb.xml

Topological criterium: Handorf
Reasoning mode: CAUTIOUS
Flux balance criterium: ON
Accumulation: ALLOWED

## Reactions occurring in all minimal solutions (intersection):

- R6
- R9

**Pull request merged**
